// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA17ovOw-qyfjv5yODWifrWpZ7u0K9iRqo',
    appId: '1:938987972177:web:3b4c4b989aab33bab1fa70',
    messagingSenderId: '938987972177',
    projectId: 'kittypow-k1ttyp0w',
    authDomain: 'kittypow-k1ttyp0w.firebaseapp.com',
    storageBucket: 'kittypow-k1ttyp0w.appspot.com',
    measurementId: 'G-YWQEMFT1BK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMSDGoAJnMrqzcor2r1Cz5ekZJY6Ap74I',
    appId: '1:938987972177:android:4c096afae47af2aeb1fa70',
    messagingSenderId: '938987972177',
    projectId: 'kittypow-k1ttyp0w',
    storageBucket: 'kittypow-k1ttyp0w.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANnfN4J6XBYeeGeGIWjswczHAx_TCQFkw',
    appId: '1:938987972177:ios:a938cc78d3308db3b1fa70',
    messagingSenderId: '938987972177',
    projectId: 'kittypow-k1ttyp0w',
    storageBucket: 'kittypow-k1ttyp0w.appspot.com',
    androidClientId: '938987972177-v40mf50bahdvf4p728ajvreprrh8givh.apps.googleusercontent.com',
    iosClientId: '938987972177-b3u4341ibjr83te872jca2tnn2r57p11.apps.googleusercontent.com',
    iosBundleId: 'com.example.cat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANnfN4J6XBYeeGeGIWjswczHAx_TCQFkw',
    appId: '1:938987972177:ios:91e84397b6a5271db1fa70',
    messagingSenderId: '938987972177',
    projectId: 'kittypow-k1ttyp0w',
    storageBucket: 'kittypow-k1ttyp0w.appspot.com',
    androidClientId: '938987972177-v40mf50bahdvf4p728ajvreprrh8givh.apps.googleusercontent.com',
    iosClientId: '938987972177-n1u27rh9k6snvr7eertuomb2fuusdb5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.cat.RunnerTests',
  );
}
